-- Copyright (C) 2018  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details.

-- Generated by Quartus Prime Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition
-- Created on Tue May 12 04:35:39 2026

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY robot_line_follower_fsmV2 IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        leftSensor : IN STD_LOGIC := '0';
        rightSensor : IN STD_LOGIC := '0';
        leftMotorBit0 : OUT STD_LOGIC;
        leftMotorBit1 : OUT STD_LOGIC;
        rightMotorBit0 : OUT STD_LOGIC;
        rightMotorBit1 : OUT STD_LOGIC;
        stateBit0 : OUT STD_LOGIC;
        stateBit1 : OUT STD_LOGIC;
        stateBit2 : OUT STD_LOGIC
    );
END robot_line_follower_fsmV2;

ARCHITECTURE BEHAVIOR OF robot_line_follower_fsmV2 IS
    TYPE type_fstate IS (stationary,straightLine,turningLeft,turningRight,searchLeft,searchRight);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,leftSensor,rightSensor)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= straightLine;
            leftMotorBit0 <= '0';
            leftMotorBit1 <= '0';
            rightMotorBit0 <= '0';
            rightMotorBit1 <= '0';
            stateBit0 <= '0';
            stateBit1 <= '0';
            stateBit2 <= '0';
        ELSE
            leftMotorBit0 <= '0';
            leftMotorBit1 <= '0';
            rightMotorBit0 <= '0';
            rightMotorBit1 <= '0';
            stateBit0 <= '0';
            stateBit1 <= '0';
            stateBit2 <= '0';
            CASE fstate IS
                WHEN stationary =>
                    IF (((leftSensor = '1') AND (rightSensor = '0'))) THEN
                        reg_fstate <= turningLeft;
                    ELSIF (((leftSensor = '1') AND (rightSensor = '1'))) THEN
                        reg_fstate <= straightLine;
                    ELSIF (((leftSensor = '0') AND (rightSensor = '1'))) THEN
                        reg_fstate <= turningRight;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= stationary;
                    END IF;

                    leftMotorBit1 <= '0';

                    leftMotorBit0 <= '0';

                    stateBit2 <= '0';

                    rightMotorBit1 <= '0';

                    stateBit0 <= '0';

                    rightMotorBit0 <= '0';

                    stateBit1 <= '0';
                WHEN straightLine =>
                    IF (((leftSensor = '0') AND (rightSensor = '1'))) THEN
                        reg_fstate <= turningRight;
                    ELSIF (((leftSensor = '0') AND (rightSensor = '0'))) THEN
                        reg_fstate <= stationary;
                    ELSIF (((leftSensor = '1') AND (rightSensor = '0'))) THEN
                        reg_fstate <= turningLeft;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= straightLine;
                    END IF;

                    leftMotorBit1 <= '1';

                    leftMotorBit0 <= '0';

                    stateBit2 <= '1';

                    rightMotorBit1 <= '1';

                    stateBit0 <= '1';

                    rightMotorBit0 <= '0';

                    stateBit1 <= '1';
                WHEN turningLeft =>
                    IF (((leftSensor = '1') AND (rightSensor = '1'))) THEN
                        reg_fstate <= straightLine;
                    ELSIF (((leftSensor = '0') AND (rightSensor = '0'))) THEN
                        reg_fstate <= searchLeft;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= turningLeft;
                    END IF;

                    leftMotorBit1 <= '0';

                    leftMotorBit0 <= '1';

                    stateBit2 <= '0';

                    rightMotorBit1 <= '1';

                    stateBit0 <= '0';

                    rightMotorBit0 <= '0';

                    stateBit1 <= '1';
                WHEN turningRight =>
                    IF (((leftSensor = '1') AND (rightSensor = '1'))) THEN
                        reg_fstate <= straightLine;
                    ELSIF (((leftSensor = '0') AND (rightSensor = '0'))) THEN
                        reg_fstate <= searchRight;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= turningRight;
                    END IF;

                    leftMotorBit1 <= '1';

                    leftMotorBit0 <= '0';

                    stateBit2 <= '0';

                    rightMotorBit1 <= '0';

                    stateBit0 <= '1';

                    rightMotorBit0 <= '1';
                WHEN searchLeft =>
                    IF (((leftSensor = '1') AND (rightSensor = '1'))) THEN
                        reg_fstate <= straightLine;
                    ELSIF (((leftSensor = '1') AND (rightSensor = '0'))) THEN
                        reg_fstate <= turningLeft;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= searchLeft;
                    END IF;

                    leftMotorBit1 <= '0';

                    leftMotorBit0 <= '0';

                    stateBit2 <= '1';

                    rightMotorBit1 <= '0';

                    stateBit0 <= '0';

                    rightMotorBit0 <= '1';

                    stateBit1 <= '1';
                WHEN searchRight =>
                    IF (((leftSensor = '1') AND (rightSensor = '1'))) THEN
                        reg_fstate <= straightLine;
                    ELSIF (((leftSensor = '0') AND (rightSensor = '1'))) THEN
                        reg_fstate <= turningRight;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= searchRight;
                    END IF;

                    leftMotorBit1 <= '0';

                    leftMotorBit0 <= '1';

                    stateBit2 <= '1';

                    rightMotorBit1 <= '0';

                    stateBit0 <= '1';

                    rightMotorBit0 <= '0';

                    stateBit1 <= '0';
                    stateBit1 <= '0';
                WHEN OTHERS => 
                    leftMotorBit0 <= 'X';
                    leftMotorBit1 <= 'X';
                    rightMotorBit0 <= 'X';
                    rightMotorBit1 <= 'X';
                    stateBit0 <= 'X';
                    stateBit1 <= 'X';
                    stateBit2 <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
